In [9]:
import numpy as np
import itertools as it
from pprint import pprint

## P1

In [2]:
def circle_area(r):
    return np.pi * r**2

r_list = list(np.arange(1, 10))

areas = [circle_area(r) for r in r_list]
print(areas)

[3.141592653589793, 12.566370614359172, 28.274333882308138, 50.26548245743669, 78.53981633974483, 113.09733552923255, 153.93804002589985, 201.06192982974676, 254.46900494077323]


In [16]:
np.average(areas)
np.std(areas)

83.17148587378013

In [5]:
board = np.array(np.arange(1, 10)).reshape(3, 3)
print(board)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## P2

In [10]:
def check(arr):
    last_x = sum(arr[0])
    for i in range(1, len(arr)):
        if sum(arr[i]) != last_x: return False
        
    last_y = sum(arr[:, 0])
    for i in range(len(arr[0])):
        if sum(arr[:, i]) != last_y: return False
    
    if not (last_x == last_y == (sum([arr[i, i] for i in range(len(arr))]))):
        return False
    return True
        

In [ ]:
def find_valid_solutions(nums, dim):
    solutions = []
    for perm in it.permutations(nums):
        board = np.array(perm).reshape(dim, dim)
        if check(board):
            # print(board[0[:len(board[0])])
            # print(board)
            solutions.append(board)
    return solutions
    
                  

In [14]:
nums = np.arange(1, 17)
result = find_valid_solutions(nums, 4)
print(len(result))
pprint(result)


KeyboardInterrupt: 