In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
def f(x):
    return lambda y: y * x

f(3)(3)

9

In [1]:
def fibo(n):
    if n == 1: return 1
    elif n == 2: return 1
    else: return fibo(n - 1) + fibo(n - 2)

fibo(10)

5

In [ ]:
inputs_gen=iter(open().read().split())
def input():
    return next(inputs_gen)

In [ ]:
l=[]
l.sort(key=lambda each: each.x)

In [17]:
arr = np.arange(9).reshape(3, 3)
print(arr)
print(arr.nonzero())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(array([0, 0, 1, 1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2, 0, 1, 2]))


In [5]:
# coding=utf-8
#服务端程序
# 导入模块
import socket
 
# 创建实例
sk = socket.socket()  # 使用默认参数
# 定义ip和port
ip_port = ('127.0.0.1', 5000)
# 绑定监听
sk.bind(ip_port)
# 最大连接数
sk.listen(5)
#接收数据
print("正在接收数据...")
conn, address=sk.accept()#两个值：连接对象，地址
#定义信息
msg="hello World"
#返回信息
conn.send(msg)#python版本为3.x则需要进行编码
#关闭
conn.close()

正在接收数据...


KeyboardInterrupt: 

In [ ]:
import socket
 
# 实例初始化
client = socket.socket()
 
ip_port = ('127.0.0.1', 5000)
# 连接主机
client.connect(ip_port)
# 接收主机信息
data = client.recv(1024) #每次接收缓冲区1024字节
print(data) #py3则需要解码

In [18]:
import cv2
import numpy as np

img = cv2.imread('test.jpg')

In [7]:
import nltk
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.cluster.util import cosine_distance

EXAMPLE = 'Hello Mr. Smith, how are you doing today? The weather is great, and Python is awesome. The sky is pinkish-blue. You shouldn\'t eat cardboard.'

stops = set(stopwords.words('english'))
result = [w for w in word_tokenize(EXAMPLE) if w not in stops]
print(result)



['Hello', 'Mr.', 'Smith', ',', 'today', '?', 'The', 'weather', 'great', ',', 'Python', 'awesome', '.', 'The', 'sky', 'pinkish-blue', '.', 'You', "n't", 'eat', 'cardboard', '.']


In [13]:
ps = PorterStemmer()
lem = WordNetLemmatizer()

words = ['male', 'man', 'run', 'ran', 'running']
print([ps.stem(w) for w in words])
print([lem.lemmatize(w, pos='v') for w in words])

['male', 'man', 'run', 'ran', 'run']
['male', 'man', 'run', 'run', 'run']


In [ ]:
def test(int: a, str: b):
    pass

def fibo(n):
    if