In [2]:
import numpy as np
from sklearn import preprocessing

In [3]:
input_data = np.array([[2.1, -1.9, 5.5],
                      [-1.5, 2.4, 3.5],
                      [0.5, -7.9, 5.6],
                      [5.9, 2.3, -5.8]])


In [5]:
# 二值化：所有高于0.5(阈值)的值将被转换为1，并且所有低于0.5的值将被转换为0
data_binarized = preprocessing.Binarizer(threshold=0.5).transform(input_data)
print(data_binarized)

# 平均去除


[[1. 0. 1.]
 [0. 1. 1.]
 [0. 0. 1.]
 [1. 1. 0.]]


In [6]:
input_labels = ['red', 'black', 'red', 'green', 'black', 'yellow', 'white']

encoder = preprocessing.LabelEncoder()
encoder.fit(input_labels)


LabelEncoder()

In [8]:
def quick_sort(arr):
    if len(arr) <= 1:
        return arr
    else:
        pivot = arr[0]
        less = [i for i in arr[1:] if i <= pivot]
        greater = [i for i in arr[1:] if i > pivot]
        return quick_sort(less) + [pivot] + quick_sort(greater)

print(quick_sort([1,3,2,5,2,4,6,7,8,9,0]))

[0, 1, 2, 2, 3, 4, 5, 6, 7, 8, 9]
