In [1]:
import numpy as np
import matplotlib.pyplot as plt
import sympy as sp

In [3]:
def f(K, x):
    a, b = K
    return a*x + b

def generate_data(K, n):
    '''
    K: 2*1 vector
    '''
    xs = np.random.randint(0, 100, size=(n, 1))
    ys = np.zeros(n).reshape(n, 1)
    print(xs)
    print(ys)
    
    for i in range(n):
        y = np.random.normal(loc=f(K, xs[i]), scale=1)
        # y = f(K, xs[i])
        ys[i] = y
    # print(xs)
    # print(ys)
    return np.column_stack((xs, ys))
    # return np.linalg.solve(xs, ys)

generate_data(np.array([3,11]).reshape(2, 1), 5)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[[59]
 [69]
 [85]
 [75]
 [18]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([[ 59.        , 186.68830397],
       [ 69.        , 216.48543297],
       [ 85.        , 266.78620491],
       [ 75.        , 237.10528971],
       [ 18.        ,  65.51130389]])

In [23]:
import codecs, json

l = generate_data(np.array([1,2,3,4,5]).reshape(5, 1), 5).tolist()
path = '/path.json'
json.dump(l, codecs.open(path, 'w', encoding='utf-8'), 
          seperator=(',', ':'))


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[[28.0, 11.0, 41.0, 66.0, 21.0, 541.9754800666569],
 [33.0, 24.0, 87.0, 49.0, 50.0, 788.476306012032],
 [38.0, 32.0, 21.0, 16.0, 51.0, 483.8122053672056],
 [93.0, 61.0, 13.0, 52.0, 14.0, 531.3336538811415],
 [62.0, 32.0, 64.0, 50.0, 55.0, 792.3520530184254]]

In [ ]:
# f(x) = ax1 + bx2 + cx3 + dx4 + ex5
def loss(K, x_ys):
    total = 0
    for i, x_y in enumerate(x_ys): 
        x, y = x_y[:-1], x_y[-1]     
        y_hat = f(K, x)
        square_residual = (y - y_hat) ** 2
        total += square_residual
    return total
    
def gradient(K, x):
    a, b, c, d, e = K

def gradient_descend(alpha):
    a, b, c, d, e = np.random.randint(0, 10, size=5)
    
    